files = [
    "Achievement.csv",
    "Achievement_Effort.csv",
    "Adaptability_Flexibility.csv",
    "Analytical_Thinking.csv",
    "Analyzing_Data_or_Information.csv",
    "Assisting_and_Caring_for_Others.csv",
    "Communicating_with_People_Outside_the_Organization.csv",
    "Communicating_with_Supervisors_Peers_or_Subordinates.csv",
    "Concern_for_Others.csv",
    "Consequence_of_Error.csv",
    "Contact_With_Others.csv",
    "Controlling_Machines_and_Processes.csv",
    "Coordinate_or_Lead_Others.csv",
    "Coordinating_the_Work_and_Activities_of_Others.csv",
    "Deal_With_External_Customers.csv",
    "Degree_of_Automation.csv",
    "Developing_Objectives_and_Strategies.csv",
    "Drafting_Laying_Out_and_Specifying_Technical_Devices_Parts_and_Equipment.csv",
    "Enterprising.csv",
    "Establishing_and_Maintaining_Interpersonal_Relationships.csv",
    "Estimating_the_Quantifiable_Characteristics_of_Products_Events_or_Information.csv",
    "Freedom_to_Make_Decisions.csv",
    "Frequency_of_Conflict_Situations.csv",
    "Frequency_of_Decision_Making.csv",
    "Guiding_Directing_and_Motivating_Subordinates.csv",
    "Impact_of_Decisions_on_Co-workers_or_Company_Results.csv",
    "Independence.csv",
    "Innovation.csv",
    "Inspecting_Equipment_Structures_or_Materials.csv",
    "Interpreting_the_Meaning_of_Information_for_Others.csv",
    "Investigative.csv",
    "Making_Decisions_and_Solving_Problems.csv",
    "Monitoring_Processes_Materials_or_Surroundings.csv",
    "Monitoring_and_Controlling_Resources.csv",
    "Organizing_Planning_and_Prioritizing_Work.csv",
    "Performing_for_or_Working_Directly_with_the_Public.csv",
    "Processing_Information.csv",
    "Providing_Consultation_and_Advice_to_Others.csv",
    "Realistic.csv",
    "Recognition.csv",
    "Relationships.csv",
    "Resolving_Conflicts_and_Negotiating_with_Others.csv",
    "Responsibility_for_Outcomes_and_Results.csv",
    "Scheduling_Work_and_Activities.csv",
    "Social.csv",
    "Structured_versus_Unstructured_Work.csv",
    "Support.csv",
    "Thinking_Creatively.csv",
    "Time_Pressure.csv",
    "Updating_and_Using_Relevant_Knowledge.csv",
    "Work_With_Work_Group_or_Team.csv",
    "Working_with_Computers.csv",
]

links = [
    "https://www.onetonline.org/find/descriptor/result/4.C.3.b.8/Structured_versus_Unstructured_Work.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.b.6/Organizing_Planning_and_Prioritizing_Work.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.3.d.1/Time_Pressure.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/1.C.6/Independence.csv?fmt=csv",
    "https://www.onetonline.org/explore/interests/Enterprising/Enterprising.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.b.5/Scheduling_Work_and_Activities.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.b.1/Coordinating_the_Work_and_Activities_of_Others.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.b.1/Making_Decisions_and_Solving_Problems.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.1.b.1.e/Work_With_Work_Group_or_Team.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.1.c.2/Responsibility_for_Outcomes_and_Results.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.3.a.1/Consequence_of_Error.csv?fmt=csv",
    "https://www.onetonline.org/explore/workvalues/Achievement/Achievement.csv?fmt=csv",
    "https://www.onetonline.org/explore/workvalues/Recognition/Recognition.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.3.a.4/Freedom_to_Make_Decisions.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/1.C.7.a/Innovation.csv?fmt=csv",
    "https://www.onetonline.org/explore/interests/Investigative/Investigative.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.3.a.2.a/Impact_of_Decisions_on_Co-workers_or_Company_Results.csv?fmt=csv",
    "https://www.onetonline.org/explore/workvalues/Independence/Independence.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.b.4/Guiding_Directing_and_Motivating_Subordinates.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/1.C.1.a/Achievement_Effort.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.1.b.1.g/Coordinate_or_Lead_Others.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.1.b.3/Estimating_the_Quantifiable_Characteristics_of_Products_Events_or_Information.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.a.2/Processing_Information.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/1.C.7.b/Analytical_Thinking.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.1.a.2/Monitoring_Processes_Materials_or_Surroundings.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.b.6/Providing_Consultation_and_Advice_to_Others.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.a.1/Interpreting_the_Meaning_of_Information_for_Others.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/1.C.4.c/Adaptability_Flexibility.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.a.4/Analyzing_Data_or_Information.csv?fmt=csv",
    "https://www.onetonline.org/explore/interests/Social/Social.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.b.3/Updating_and_Using_Relevant_Knowledge.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.b.2/Thinking_Creatively.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.a.7/Resolving_Conflicts_and_Negotiating_with_Others.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.b.2/Thinking_Creatively.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.1.d.1/Frequency_of_Conflict_Situations.csv?fmt=csv",
    "https://www.onetonline.org/explore/workvalues/Support/Support.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.a.4/Establishing_and_Maintaining_Interpersonal_Relationships.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.a.5/Assisting_and_Caring_for_Others.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.2.b.4/Developing_Objectives_and_Strategies.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/1.C.3.b/Concern_for_Others.csv?fmt=csv",
    "https://www.onetonline.org/explore/workvalues/Relationships/Relationships.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.1.a.4/Contact_With_Others.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.c.3/Monitoring_and_Controlling_Resources.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.1.b.1.f/Deal_With_External_Customers.csv?fmt=csv",
    "https://www.onetonline.org/explore/interests/Realistic/Realistic.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.3.a.2.b/Frequency_of_Decision_Making.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.a.2/Communicating_with_Supervisors_Peers_or_Subordinates.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.3.a.3/Controlling_Machines_and_Processes.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.b.6/Providing_Consultation_and_Advice_to_Others.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.a.3/Communicating_with_People_Outside_the_Organization.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.1.b.2/Inspecting_Equipment_Structures_or_Materials.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.3.b.2/Drafting_Laying_Out_and_Specifying_Technical_Devices_Parts_and_Equipment.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.C.3.b.2/Degree_of_Automation.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.4.a.8/Performing_for_or_Working_Directly_with_the_Public.csv?fmt=csv",
    "https://www.onetonline.org/find/descriptor/result/4.A.3.b.1/Working_with_Computers.csv?fmt=csv",
]

import pprint

i = 0

count = {}

for l in set(links):
    count[l] = 0

for f in files:
    for l in set(links):
        if f == l.split("/")[-1].replace("?fmt=csv", ""):
            count[l] += 1
            i += 1
            flag = False
            break
print(len(set(links)), len(count), len(files), i, i == len(files))
pprint.pprint(count)
