SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS jobProfile;
DROP TABLE IF EXISTS profileCriteria;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS survey;
DROP TABLE IF EXISTS questionAcceptableAnswer;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS response;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS criteria;
DROP TABLE IF EXISTS onet;
DROP TABLE IF EXISTS accountProfile;
DROP TABLE IF EXISTS responseProfile;

SET FOREIGN_KEY_CHECKS = 1;